modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/ikunkk02-afk/Tactical-Loot/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/ikunkk02-afk/Tactical-Loot"
logoFile="assets/tactical_pickup/icon.png"
authors="寿云"
description='''
Tactical Loot provides a server-validated HUD and tactical interface for selecting,
filtering, picking up, placing, and discarding nearby dropped items.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
